#!/bin/bash
#PBS -N grouped
#PBS -l nodes=2:ppn=8,walltime=00:15:30

GSL_IEEE_MODE="double-precision,"\
"mask-underflow,"\
"mask-denormalized"

cd /home/aferrari/code/PhD-code
export OMP_NUM_THREADS=16
